Allow number input to set an error if input is not valid
BLSQ/bluesquare-components pull request #134
Opened 2023-11-14 10:29 UTC by beygorghor

Pass setFieldError to invalidate parent form and disable save legend or org unit coordinates.
Fix is done on same branch in Iaso

2023-11-23 16:49 UTC, quang-le reviewed
Looks Ok but from what I see, it will only work with formik, so we won't be able to display errors in a filter for example

2023-11-27 11:12 UTC, quang-le requested changes
I'm not sure about this. It works for sure, so no complaints here. 
But on the one hand we have to pass a function setting the errors and an array of errors, but on the other hand, the messages come from the component.
Since we need to pass props to handle the error state anyway, we might as well remove the internal error handling from the component. On the other hand, having an internal error state may be useful if we use the component outside of a form, eg in a filter, but then we should be able to use it without passing additional props.

Long stories short we should either:
- remove the internal error state entirely
- make the `errors` and `setFieldErrors` props optional

2023-11-28 12:12 UTC, beygorghor commented
After discussion i created a ticket to uniformise all error handling ([IA-2538](https://bluesquare.atlassian.net/browse/IA-2538))

2023-11-28 16:45 UTC, quang-le approved these changes

2023-11-28 16:46 UTC, quang-le approved these changes

2023-11-28 16:46 UTC, merged