IA-650 react table
BLSQ/bluesquare-components pull request #6
Opened 2021-08-24 12:10 UTC by beygorghor

New table component using react-table hooks

2021-08-24 12:41 UTC, olethanh commented on src/components/table/Table/PageRowSelect.js
> +    const { formatMessage } = intl;
you can directly use `const { formatMessage } = useSafeIntl();`

2021-08-25 10:53 UTC, olethanh requested changes

2021-08-25 10:53 UTC, olethanh commented on src/components/table/Table/tableUtils.js
> +export { getTableUrl };
why put it on a separated line?

2021-08-25 10:53 UTC, olethanh commented on src/components/table/Table/tableUtils.js
> +            defaultMessage: 'Un select all',
unselect in one word

2021-08-25 10:53 UTC, olethanh commented on src/components/table/Table/tableUtils.js
> +            };
I think you can just do newColumns[i].Header=

2021-08-25 10:53 UTC, olethanh commented on src/css/index.scss
>  @import "maps";
yay removal. I think you can even remove leafletCluster and amps since they are not used in bluesquare-components

2021-08-25 10:53 UTC, olethanh commented on src/components/table/Table/TablePaginationActions.js
> +    const { formatMessage } = intl;
idem

2021-08-25 15:31 UTC, quang-le requested changes
Very nice! I still have to get acquainted with react-table 7, but I feel the code is much more approachable than the previous table.

Most comments are style, or nitpicking but there's a few questions I'm curious to hear the answer of, so I'm going to "request changes".

Very nice work

2021-08-25 15:31 UTC, quang-le commented on src/components/table/Table/NoResult.js
> +        return (
data?.length

2021-08-25 15:31 UTC, quang-le commented on src/components/table/Table/index.js
> +    const intl = useSafeIntl();
You can deconstruct the props directly :
```javascript
const Table = ({ params, count, extraProps, ...}) => { // ... } 
```

2021-08-25 15:31 UTC, quang-le commented on src/components/table/Table/index.js
> +        if (
why not adding it to the declaration on line 73?

2021-08-25 15:31 UTC, quang-le commented on src/components/table/Table/index.js
> +import MaUTable from '@material-ui/core/Table';
MuiTable to stay consistent with eg css classes?

2021-08-25 15:31 UTC, quang-le commented on src/styles/iaso/theme.js
> -        // },
Finally, this commented code is gone 😅

2021-08-31 09:10 UTC, olethanh commented on src/components/table/Table/index.js
> +    const data = useMemo(() => props.data, [props.data]);
for the dependency array, react doesn't do a deep comparison but check  using Object.is(), so if the object changed it just return itself when it's a new object and thus don't do anything
https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update

2021-08-31 09:17 UTC, merged